### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by Ex0tiik** [mirorauhala/brackets-bootstrap-skeleton#18]
Hello guys, i'm using Bootstrap Version 1.4 edition 1.4.0-16380 (release 273804eb3), and the plugin doesn't work anymore. It's a know-issue or i'm taking bad with the use?

I try : 
- Create a new document:
- Place my cursor in this new-document 
- Open New and click on "New Bootstrap 3 Document"

But Nothing done. An idea? :-)

Thanks!

**Comment by mirorauhala** [comment]
Yes!
I have noticed the same issue also when I had to do couple prototypes.
Also noticed as the extension fetches the latest version of bootstrap (so I don't have to be updating it all the time manually) it will use the latest and greatest bootstrap 4.0-alpha which doesnt have any CDNs in place right now. Plus it would then leave the 4.0-alpha to all CDN URLs which wouldn't be a great thing.

Can't really say much. I will try to fix this once I get some time to figure the changes Brackets team has done to the API. Meanwhile working on couple closed projects. Can't really say much other than go visit our LAN Party page at https://beta.pixelity.fi
Sorry only available in Finnish at the moment.

**Comment by le717** [comment]
It's not a Brackets API issue, just poor coding on my part when #10 was implemented. :oops:

Basically, it is retrieving the latest Bootstrap version but not actually returning anything. That's because I wrote it to only check the latest release if _not_ a prerelease and use it if so. The latest Bootstrap release _is_ a prerelease, thus it fails. It needs to find the latest non-prereleae and use that.

Now, this whole setup might post an issue when v4 comes out (because v3 [will still be supported](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/#supporting-v3) and depending on the latest release it might flip-flop between v3 and v4, but v4 probably won't be out this year (or at least for a while), so we can cross that when we get there. :)
